export const errors = {
  "create_doc_after_registration": "Create doc after registration",
  "sign_up": "Sign up",
  "get_user_by_id": "Get user by id",
  "send_phone_verification_sms": "Send phone verification sms",
  "verify_phone_code": "Verify phone code",
  "create_business": "Create business",
  "send_business_verify_email": "Send business verify email",
  "create_user": "Create user",
  "user": "User",
  "send_verify_email": "Send verify email",
  "reset_password_email": "Reset password email",
  "verify_code_from_email": "Verify code from email",
  "add_customer": "Add customer",
  "add_vendor": "Add vendor",
  "update_business": "Update business",
  "update_business_address": "Update business address",
  "get_business_customers": "Get business customers",
  "get_business_vendors": "Get business vendors",
  "delete_vendor": "Delete vendor",
  "delete_customer": "Delete customer",
  "update_business_by_creator": "Update business by creator",
}