export const TABLES = {
  BusinessCategory: "Business category",
  Business: "Businesses",
  Currency: "Currency",
  VendorCustomer: "Vendor - Customer",
  Users: "Users",
  LegalAgreements: "Legal agreements",
  DocumentHeader: "Document_header",
  DocumentItems: "Document items",
  DocumentTransactions: "Document transactions",
  StaticData: "Static data",
  PaymentServices: "Payment services",
  VerifyEmail: "Verify email",
  UserPlan: "User plans",
  CountryCode: "Country code",
  PhoneAreaCode: "Phone area code",
  Messages: "Messages",
  UserPhoneVerification: "Verify phone",
  UserBusiness: "User - Business",
};
