openapi: 3.0.3
info:
  title: Paylist API
  version: 1.0.0
  description: API documentation for authentication and payment endpoints

servers:
  - url: http://localhost:3000/api

paths:
  /register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: user@example.com
                password:
                  type: string
                  example: mysecurepassword
              required:
                - email
                - password
      responses:
        '201':
          description: User registered successfully
        '400':
          description: Invalid input

  /login:
    post:
      summary: Login user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: user@example.com
                password:
                  type: string
                  example: mysecurepassword
              required:
                - email
                - password
      responses:
        '200':
          description: Login successful
        '401':
          description: Unauthorized

  /pay/initiate:
    post:
      summary: Initiate payment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                  example: 5000
                currency:
                  type: string
                  example: GBP
                reference:
                  type: string
                  example: txn_123456
              required:
                - amount
                - currency
                - reference
      responses:
        '200':
          description: Payment initiated
        '400':
          description: Invalid payment request

  /pay/verify:
    post:
      summary: Verify payment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                reference:
                  type: string
                  example: txn_123456
              required:
                - reference
      responses:
        '200':
          description: Payment verified
        '404':
          description: Transaction not found